on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 1 * *"

jobs:
  AMIBuilder:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::683290208331:role/GitHubWorkflow
          role-session-name: GitHubWorkflow

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.11.0"

      - name: Packer Init
        run: |
          packer init .

      - name: Packer Build Deployable Image
        if: github.ref == 'refs/heads/main'
        run: |
          packer build \
          -var "deploy_to_all_environments=True" .

      - name: Packer Build Test Image
        if: github.ref != 'refs/heads/main'
        run: |
          packer build \
          -var "deploy_to_all_environments=False" .
